#include <stdlib.h>
#include "cards.h"

// helps set the card_t constant and labels out all possible combinations of cards
const card_t  uno[108] = {
      COLOR_RED | RANK_CERO,
    COLOR_RED | RANK_UNO,     COLOR_RED | RANK_UNO,
    COLOR_RED | RANK_DOS,     COLOR_RED | RANK_DOS,
    COLOR_RED | RANK_TRES,   COLOR_RED | RANK_TRES,
    COLOR_RED | RANK_CUATRO,    COLOR_RED | RANK_CUATRO,
    COLOR_RED | RANK_CINCO,    COLOR_RED | RANK_CINCO,
    COLOR_RED | RANK_SEIS,     COLOR_RED | RANK_SEIS,
    COLOR_RED | RANK_SIETE,   COLOR_RED | RANK_SIETE,
    COLOR_RED | RANK_OCHO,   COLOR_RED | RANK_OCHO,
    COLOR_RED | RANK_NUEVE,    COLOR_RED | RANK_NUEVE,
    COLOR_RED | RANK_SKIP,    COLOR_RED | RANK_SKIP,
    COLOR_RED | RANK_TWO, COLOR_RED | RANK_TWO,
    COLOR_RED | RANK_REVERSAL, COLOR_RED | RANK_REVERSAL,

    COLOR_GREEN | RANK_CERO,
    COLOR_GREEN | RANK_UNO,     COLOR_GREEN | RANK_UNO,
    COLOR_GREEN | RANK_DOS,     COLOR_GREEN | RANK_DOS,
    COLOR_GREEN | RANK_TRES,   COLOR_GREEN | RANK_TRES,
    COLOR_GREEN | RANK_CUATRO,    COLOR_GREEN | RANK_CUATRO,
    COLOR_GREEN | RANK_CINCO,    COLOR_GREEN | RANK_CINCO,
    COLOR_GREEN | RANK_SEIS,     COLOR_GREEN | RANK_SEIS,
    COLOR_GREEN | RANK_SIETE,   COLOR_GREEN | RANK_SIETE,
    COLOR_GREEN | RANK_OCHO,   COLOR_GREEN | RANK_OCHO,
    COLOR_GREEN | RANK_NUEVE,    COLOR_GREEN | RANK_NUEVE,
    COLOR_GREEN | RANK_SKIP,    COLOR_GREEN | RANK_SKIP,
    COLOR_GREEN | RANK_TWO, COLOR_GREEN | RANK_TWO,
    COLOR_GREEN | RANK_REVERSAL, COLOR_GREEN | RANK_REVERSAL,

    COLOR_YELLOW | RANK_CERO,
    COLOR_YELLOW | RANK_UNO,     COLOR_YELLOW | RANK_UNO,
    COLOR_YELLOW | RANK_DOS,     COLOR_YELLOW | RANK_TWO,
    COLOR_YELLOW | RANK_TRES,   COLOR_YELLOW | RANK_TRES,
    COLOR_YELLOW | RANK_CUATRO,    COLOR_YELLOW | RANK_CUATRO,
    COLOR_YELLOW | RANK_CINCO,    COLOR_YELLOW | RANK_CINCO,
    COLOR_YELLOW | RANK_SEIS,     COLOR_YELLOW | RANK_SEIS,
    COLOR_YELLOW | RANK_SIETE,   COLOR_YELLOW | RANK_SIETE,
    COLOR_YELLOW | RANK_OCHO,   COLOR_YELLOW | RANK_OCHO,
    COLOR_YELLOW | RANK_NUEVE,    COLOR_YELLOW | RANK_NUEVE,
    COLOR_YELLOW | RANK_SKIP,    COLOR_YELLOW | RANK_SKIP,
    COLOR_YELLOW | RANK_TWO, COLOR_YELLOW | RANK_TWO,
    COLOR_YELLOW | RANK_REVERSAL, COLOR_YELLOW | RANK_REVERSAL,

    COLOR_BLUE | RANK_CERO,
    COLOR_BLUE | RANK_UNO,     COLOR_BLUE | RANK_UNO,
    COLOR_BLUE | RANK_DOS,     COLOR_BLUE | RANK_DOS,
    COLOR_BLUE | RANK_TRES,   COLOR_BLUE | RANK_TRES,
    COLOR_BLUE | RANK_CUATRO,    COLOR_BLUE | RANK_CUATRO,
    COLOR_BLUE | RANK_CINCO,    COLOR_BLUE | RANK_CINCO,
    COLOR_BLUE | RANK_SEIS,     COLOR_BLUE | RANK_SEIS,
    COLOR_BLUE | RANK_SIETE,   COLOR_BLUE | RANK_SIETE,
    COLOR_BLUE | RANK_OCHO,   COLOR_BLUE | RANK_OCHO,
    COLOR_BLUE | RANK_NUEVE,    COLOR_BLUE | RANK_NUEVE,
    COLOR_BLUE | RANK_SKIP,    COLOR_BLUE | RANK_SKIP,
    COLOR_BLUE | RANK_TWO, COLOR_BLUE | RANK_TWO,
    COLOR_BLUE | RANK_REVERSAL, COLOR_BLUE | RANK_REVERSAL,

    COLOR_NONE | RANK_RAINBOW,
    COLOR_NONE | RANK_RAINBOW,
    COLOR_NONE | RANK_RAINBOW,
    COLOR_NONE | RANK_RAINBOW,

    COLOR_NONE | RANK_RAINBOWFOUR,
    COLOR_NONE | RANK_RAINBOWFOUR,
    COLOR_NONE | RANK_RAINBOWFOUR,
    COLOR_NONE | RANK_RAINBOWFOUR

};

// Shuffles the deck
//Sets card_t and size_t as constants for convenience and effeciency
void shuffle(card_t* deck, size_t cards)
{
    size_t  i = cards;

    while (i > 1) {
        const size_t  k = rand() % i;
        const card_t  temp = deck[k];
        i--;

        deck[k] = deck[i];
        deck[i] = temp;
    }
}